sonar.projectKey=node-calc-api
sonar.organization=welantoniosantana

sonar.sources=.
sonar.exclusions=node_modules/**,**/dist/**
sonar.tests=test
sonar.test.inclusions=**/*_test.js,**/*_spec.js

# Configurações de cobertura de código
sonar.javascript.lcov.reportPaths=coverage/lcov.info